//CommonSmartTool.h
//Original Generated by MakeOID20130807.1
//HEAVILY MODIFIED TO INCLUDE Extended Common Smart Tool Code
//Not to be replaced.  Requires Hand Merge
#ifndef CommonSmartTool_H
#define CommonSmartTool_H
//Includes needed for common SmartTool Type
#include "SmartTool.h"
#include "STP.h"

//MakeOID-Section:: CommonOID Enum
enum CommonOID
{
	COMMON_OID_NULLOID = 0,
	COMMON_OID_DEBUG = 1,
	COMMON_OID_SMARTTOOL_TYPE = 2,
	COMMON_OID_SMARTTOOL_SUBTYPE = 3,
	COMMON_OID_SYSTEM_VERSION = 4,
	COMMON_OID_SERIAL_NUMBER = 5,
	COMMON_OID_RESET_SYSTEM = 6,
	COMMON_OID_SCRIPT_TRANSFER = 7,
	COMMON_OID_GENERICMESSAGE = 8,
	COMMON_OID_DEBUGMESSAGE = 9,
	COMMON_OID_STPSTATUS = 10,
	COMMON_OID_COMMON_MESSAGE_CODE = 11,
	COMMON_OID_CONTROL_DELAY = 12,
	COMMON_OID_DIRECT_DOUT = 13,
	COMMON_OID_DIRECT_DIN = 14,
	COMMON_OID_COM_VERSION = 15,
	COMMON_OID_STREAM_SYNC = 16,
	COMMON_OID_STP_CLOSE = 17,
	COMMON_OID_STP_IDENTIFY = 18,
	COMMON_OID_DATE_TIME = 19,

	COMMON_OID_MAX_NUMBER = 20

};
//MakeOID-Section::END

//MakeOID-Section:: Common Value Defines
// STPSTAT value association
enum STPSTAT //ushort
{
	STPSTAT_OK = 0,
	STPSTAT_NOSUCHOID = 1,
	STPSTAT_VALOVERMAX = 2,
	STPSTAT_VALUNDERMIN = 3,
	STPSTAT_BADLENGTH = 4,
};

// STPCLOSEREASON value association
enum STPCLOSEREASON //byte
{
	CLOSE_COMPLETE = 0,
	CLOSE_REQUESTED = 1,
	CLOSE_TIMEOUT = 2,
	CLOSE_SYNC = 3,
	CLOSE_ERROR = 4,
};

//MakeOID-Section::END

//MakeOID-Section:: TYPEDEFS (oid complete)

typedef struct
{
	unsigned int uiOID;
	unsigned int uiStatus;
} td_StpStatus;

typedef struct
{
	unsigned int uiOID;
	unsigned int uiCode;
} td_oid_common_message_code;

typedef struct
{
	char cchannel;
	char cvalue;
} td_oid_direct_dout;

typedef struct
{
	char cchannel;
	char cvalue;
} td_oid_direct_din;

typedef struct
{
	unsigned long ulticksMSW;
	unsigned long ulticksLSW;
	unsigned int uiyear;
	char cmonth;
	char cdayOfMonth;
	char chour;
	char cminute;
	char csecond;
	unsigned int uimillisecond;
} td_DateTime;

//MakeOID-Section::END

//MakeOID-Section:: Global Smart Tool ID And Version Constant Defines 

//Common doesn't have it's own COM version or version at this time

extern char * pszOIDNamesCommon[];

//MakeOID-Section:: CONFIG TYPEDEF AND PREDECLARATION

//Common has no config oids

//MakeOID-Section::END

//MakeOID-Section:: GLOBAL PREDECLARATIONS (for header)

extern char g_szSerialNumber[64];
extern td_StpStatus g_StpStatus;
extern td_DateTime g_DateTime;
//MakeOID-Section::END

//MakeOID-Section:: FUNCTION PREDECLARATIONS

//MakeOID-Section::END

//OID Handling Functions

//Maintain g_DateTime
void ServiceDateTime();
void HandleCommonOIDDateTimeGet(td_STPsessions * p_STPSession);
void HandleCommonOIDDateTimeSet(td_DateTime * p_DateTime);

#endif
