//MiniFTSmartTool.c
//Generated by MakeOID20131018.1 
//Preserve any customized code if required.
#include "MiniFTSmartTool.h"



//MakeOID-Section:: OID NAMES ARRAY

char * pszOIDNamesMiniFT[] = {
	"MINIFT_MESSAGE_CODE",
	"MODE",
	"ACTION",
	"RESET_MC",
	"ENCODER_RATIO",
	"MC_CURRENT_LIMITS",
	"MC_PEAK_CURRENT_LIMITS",
	"BRAKE_ON_TIMEOUT",
	"MCERR",
	"STOREDEFAULT_CONFIG",
	"RECALL_CONFIG",
	"EEOPTION_DEFAULT",
	"EEOPTION",
	"BEEPER",
	"SYSTEM_MONITOR",
	"AIR_PRESSURE",
	"LIMITS_AND_OBSTRUCTIONS",
	"TOOL_VERIFYENABLE",
	"HOLE_PARAMETERS",
	"TOOL_RESERVED",
	"PROCESS",
	"RETURN_HEIGHT",
	"GAUGE_LENGTH",
	"SCALE_MODE",
	"RESERVED_2",
	"PARTPGM_CLEAR",
	"PARTPGM_REQUEST_FILE",
	"PARTPGM_DIR",
	"PARTPGM_NAME",
	"PARTPGM_DATA",
	"PARTPGM_CHECKSUM",
	"PARTPGM_LINEARJOB",
	"PARTPGM_STATUS",
	"PARTPGM_LOCKED",
	"STARTOVER",
	"LOAD_YRAIL",
	"GRAVCOMP_STATUS",
	"GRAVCOMP_AXES",
	"GRAVCOMP_CMD",
	"GRAVCOMP_FLOAT",
	"GRAVCOMP_SPEED",
	"GRAVCOMP_ACCEL",
	"GRAVCOMP_DECEL",
	"GRAVCOMP_MOVEDIST",
	"GRAVCOMP_ALGORITHM",
	"GRAVCOMP_NOISE_LIMIT",
	"GRAVCOMP_TRIGGERFACTOR",
	"FLOAT_STATUS",
	"GRAVCOMP_RESULTS",
	"FLOAT_SPEEDLIMIT",
	"JOG_SPEEDLIMIT",
	"MAX_SPEED_X",
	"MAX_SPEED_Y",
	"X_RAIL_SURFACE_OFFSET",
	"PROBE_METHOD",
	"PROBE_METHOD_DEFAULT",
	"PROBE_OFFSET",
	"PROBEDIR",
	"DRILLDIR",
	"KHOLE_MAX_DISTANCE_ERROR",
	"APPROX_LOCATION_ERROR",
	"KHOLE_DISTANCE",
	"PROBE",
	"PROBE_POSITION",
	"PROBE_STATUS",
	"PROBE_START",
	"PROBE_ACCEPT_REQUIRED",
	"HOME",
	"HOME_SPEED",
	"HOME_ACCEL",
	"HOME_DECEL",
	"HOME_MOVEDIST",
	"PROBE_ADJUST",
	"PROBE_ADJUST_LIMIT",
	"HOME_FINE_SPEED",
	"HOME_REPORT",
	"PATTERN",
	"POSNMODE_CURPOSN",
	"POSNMODE_NEARPOSN",
	"POSNMODE_GOALPOSN",
	"POSNMODE_CURXY",
	"POSNMODE_NEARXY",
	"POSNMODE_POSNSUMMARY",
	"POSNMODE_MOVETONEXT",
	"POSNMODE_MOVETOPREV",
	"POSNMODE_MOVETOIND",
	"POSNMODE_MOVEAGAIN",
	"POSNMODE_MOVETYPE",
	"POSNMODE_PREMOVEXY",
	"POSNMODE_SPEED",
	"POSNMODE_ACCEL",
	"POSNMODE_DECEL",
	"POSNMODE_FINALSPEED",
	"ORTHO_SLOPE",
	"POSNERR_LIMIT",
	"POSNMODE_TOLERANCE",
	"VELERR_LIMIT",
	"LONG_DISTANCE",
	"LONG_SPEED",
	"POSNMODE_MOVEDONE",
	"OP_STARTED",
	"OP_HISTORY",
	"DRILL_HOLE_ONE_TIME",
	"AUTOMOVE",
	"AUTOMOVE_DELAY",
	"AUTOREPEAT",
	"MACHINE_OFFSET",
	"MACHINE_OFFSET_CADJ",
	"MACHINE_OFFSET1",
	"MACHINE_OFFSET2",
	"STATION",
	"TOOL_OFFSET",
	"TOOL_FLIP",
	"DRIVE_THROUGH_BACKLASH",
	"DRILL_OFFSET1",
	"DRILL_OFFSET2",
	"OFFSET_SEAL",
	"OFFSET_FILL",
	"JOG",
	"JOG_SPEED",
	"JOG_ACCEL",
	"JOG_DECEL",
	"JOG_FACTOR",
	"HOME_POSITION_Y_POS",
	"POSITION_LIMIT_Y_POS",
	"HOME_POSITION_Y_NEG",
	"POSITION_LIMIT_Y_NEG",
	"PROBE_REGISTRATION",
	"OBSTRUCTION_CODE_MASK",
	"MACHINE_LOCK_REQUIRED",
	"MACHINE_LOCK",
	"CLAMP",
	"ALOCK",
	"ALOCKDELAY",
	"AUNLOCKDELAY",
	"LEGSLOCKDELAY",
	"LEGSUNLOCKDELAY",
	"LEGSUPDELAY",
	"LEGSDOWNDELAY",
	"LOWPRESSUREDELAY",
	"LOWPRESSUREDOWNDELAY",
	"PRESSUREDELAY",
	"PRESSUREDOWNDELAY",
	"LOWPRESSURE",
	"PRESSURE",
	"AIR_CLEAR",
	"LASER_SENSOR_OFFSET",
	"CAM_OFFSET",
	"VISION_INSPECT",
	"VISION_IMAGE",
	"VISION_DATA",
	"VISION_INSPECT_RESULTS",
	"LS_ALG_PARAM",
	"CAM_ALG_PARAM",
	"LS_AUTO_INSPECT",
	"STOP_INTERFACE_TASK",
	"PROCESS_START",
	"PROCESS_STOP",
	"PROCESS_CONTINUE_MODE",
	"PROCESS_OPERATIONS",
	"DRILL_STATE",
	"DRILL_EXPLANATION",
	"DRILL_EXPLANATION_DATA",
	"SEAL_STATE",
	"SEAL_CLAMP",
	"SEAL_PRESSURE_DELAY",
	"SEAL_PRESSURE_RELEASE_DELAY",
	"SEAL_PRIME_DELAY",
	"SEAL_GLOB_DELAY",
	"SEAL_APPLY_DELAY",
	"FILL_STATE",
	"FILL_CLAMP",
	"FILL_EXTEND_DELAY",
	"FILL_RAM_DELAY",
	"FASTENER_REQUEST",
	"FASTENER_ARRIVED",
	"FASTENER_POST_DELAY",
	"ACCEL_ARM",
	"ACCEL_TRIGGER",
	"TOOL_Z_BASE",
	"FASTENER_FAULT",
	"POSNMODE_ACTIVE_PREMOVEXY",
	"DRILL_FAULT",
	"HOLE_RESULT_DATA",
	"MOVEXY",
	"POSN_DISPLAY",
	"POSNMODE_XYDATA_ID",
	"POSNMODE_XYDATA",
	"RFID_CONFIG",
	"RFID_DATA",
	"HOME_RFID",
	"READ_RFID",
	"HOME_STOP",
	"ESTOP_CLEAR_DELAY",
	"DRILL_BUTTON_DELAY",
	"USE_CUTTER_DETECT",
	"JOG_ENABLE_TIMEOUT",
	"DRILL_CYCLE_DELAY",
	"INSPECT_METHOD",
	"COMMAND_INSPECT_METHOD",
	"FORCE_SENSOR_CALIBRATION",
	"FORCE_SENSOR",
	"FORCE_LIMITS",
	"PROBE_FLAGS",
	"MO_CAL",
	"VISION_EXTERNAL_ANALYSIS",
	"LAO_WARNINGS",
	"RFID_TAG_SET",
	"PROBE_UPDATE_NOW",
	"KHOLE_MAX_DISTANCE_CHECK",
	"MAX_EDGE_SHIFT_PROBE_ACCEPT",
	"ALLOW_DRILL_BEYOND_SHIFT_LIMITS",
	"NAC_SERIAL_NUMBER",
	"Y_RETRACT",
	"SYSTEM_COMPONENTS",
	"RFID_TAG_SET2",
	"SPRITZ_DURATION_MS",
	"BURST_ON_DURATION_MS",
	"BURST_INTERVAL_MS",
	"ANGLE_SENSOR_A_NEG_CALIBRATION",
	"ANGLE_SENSOR_A_POS_CALIBRATION",
	"ANGLE_SENSOR_LEVEL_NOW",
	"ANGLE_SENSOR_A_BASE_WIDTH",
	"ANGLE_SENSOR_MC_CALIBRATION",
	"AAXIS_MOVE_SPEED",
	"CLAMP_STRAIN",
	"OID_MAX_NUMBER_MiniFT"
};

//MakeOID-Section::END


//MakeOID-Section:: Global Smart Tool ID And Version Constant Defines 

const char * SmartToolTypeMiniFT = "MiniFt";

const char * MiniFTSysVersion = "null";

const uint16 MiniFTCOMVersion = 2;

td_SmartTool g_MiniFTSmartTool = { "MiniFt", 100, MINIFT_OID_MAX_NUMBER, pszOIDNamesMiniFT };



//MakeOID-Section:: CONFIG DECLARATION

td_ConfigData g_ConfigData;

//MakeOID-Section::END


//MakeOID-Section:: GLOBAL DECLARATIONS

byte g_cModeState = 0;
byte g_cAction = ACTION_IDLE;
byte g_cEEOption = EENONE;
td_HoleParam g_HoleParam = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
byte g_cLoadedProcess = 0;
float g_fGaugeLength = 0;
char g_szPartPgmFilename[MAX_FILENAME_LEN] = "";
byte g_cPartPgmStatus = 0;
byte g_cGravCompStatus = 0;
byte g_cFloatStatus = 0;
td_GravCompResults g_GravCompResults = {  0, 0, 0, 0 };
float g_fXRailSurfaceOffset = 2;
byte g_cProbeMethod = 0;
byte g_cPattern = 0;
byte g_cMoveDone = 1;
td_MachineOffset g_MachineOffset = {  0, 0 };
byte g_cMachineOffsetCompensationAdjustment = 0;
td_MachineOffset1 g_MachineOffset1 = {  0, 0, 0 };
td_MachineOffset2 g_MachineOffset2 = {  0, 0, 0 };
byte g_cStation = STATION_UNSPEC;
td_JogFactor g_JogFactor = {  1.0, 1.0 };
byte g_cALockMode = 0;
td_VisionInspectResults g_VisionInspectResults = {  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
byte g_cDrillState = 0;
byte g_cDrillExplanation = 0;
byte g_cSealState = 0;
byte g_cFillState = 0;
byte g_cFastenerArrived = 0;
byte g_cAccelArm_ = 0;
byte g_cAccelTrigger_ = 0;
td_FastenerFault g_FastenerFault = {  0, 0, 0 };
td_DrillFault g_DrillFault = {  0, 0, 0 };
td_HoleResultData g_HoleResultData = {  0, 0 };
td_RFIDData g_RFIDData = {  RFID_INIT, RFID_CONTEXT_SEEK, RFID_SEEK_NULL, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
byte g_szTagDatalen = 0;
char g_szTagData[65] = "\0";
byte g_cReadRFID = RFID_READ_OFF;
td_ForceSensor g_ForceSensor = {  0, 0, 0, 0 };
//MakeOID-Section::END


//MakeOID-Section:: CONFIG DEFAULTS

void MiniFTInitConfig(void)
{
	//FIXME PORTMED  should swap these out to better defaults OR don't even bother and just deal with loading...
	g_ConfigData.EncoderRatio.fX = 245858.9;
	g_ConfigData.EncoderRatio.fY = 245858.9;
	g_ConfigData.MCCurrentLimit.fX = 7.5;
	g_ConfigData.MCCurrentLimit.fY = 6.0;
	g_ConfigData.MCPeakCurrentLimit.fX = 7.5;
	g_ConfigData.MCPeakCurrentLimit.fY = 6.0;
	g_ConfigData.uiBrakeOnTimeout = 4000;
	g_ConfigData.cEEOptionDefault = EENONE;
	g_ConfigData.cbeeper = 1;
	g_ConfigData.cToolVerifyEnable = TOOLVERIFY_PRE;
	g_ConfigData.fReturnHeight = 0;
	g_ConfigData.cScaleMode = 0;
	g_ConfigData.cGravCompAxes = 0;
	g_ConfigData.GravCompSpeed.fX = 0.45;
	g_ConfigData.GravCompSpeed.fY = 0.45;
	g_ConfigData.GravCompAcc.fX = 8.0;
	g_ConfigData.GravCompAcc.fY = 8.0;
	g_ConfigData.GravCompDec.fX = 8.0;
	g_ConfigData.GravCompDec.fY = 8.0;
	g_ConfigData.GravCompMoveDist.fX = 0.25;
	g_ConfigData.GravCompMoveDist.fY = 0.25;
	g_ConfigData.cGravCompAlgorithm = GC_ORIGINAL;
	g_ConfigData.GravCompNoiseLimit.fX = 4.0;
	g_ConfigData.GravCompNoiseLimit.fY = 4.0;
	g_ConfigData.GravCompTriggerFactor.fX = 0.1;
	g_ConfigData.GravCompTriggerFactor.fY = 0.1;
	g_ConfigData.fFloatSpeedLimit = 40;
	g_ConfigData.fJogSpeedLimit = 40;
	g_ConfigData.fMaxSpeedX = 1;
	g_ConfigData.fMaxSpeedY = 1;
	g_ConfigData.cProbeMethodDefault = PROBE_MANUAL;
	g_ConfigData.ProbeOffset.fX = 0;
	g_ConfigData.ProbeOffset.fY = 0;
	g_ConfigData.iProbeDir = 0;
	g_ConfigData.iDrillDir = 0;
	g_ConfigData.fMaxKholeDistanceError = 0.1;
	g_ConfigData.fApproxLocationError = 0.6;
	g_ConfigData.cProbeAcceptRequired = 0;
	g_ConfigData.HomeSpeed.fX = 0.50;
	g_ConfigData.HomeSpeed.fY = 0.50;
	g_ConfigData.HomeAcc.fX = 8.0;
	g_ConfigData.HomeAcc.fY = 8.0;
	g_ConfigData.HomeDec.fX = 8.0;
	g_ConfigData.HomeDec.fY = 8.0;
	g_ConfigData.HomeMoveDist.fX = 1.0;
	g_ConfigData.HomeMoveDist.fY = 1.0;
	g_ConfigData.fProbeAdjustLimit = 0.1;
	g_ConfigData.HomeFineSpeed.fX = 0.05;
	g_ConfigData.HomeFineSpeed.fY = 0.05;
	g_ConfigData.cMoveType = MOVETYPE_FAST;
	g_ConfigData.PreMove.fX = 0.2;
	g_ConfigData.PreMove.fY = 0.2;
	g_ConfigData.PosnSpeed.fX = 4.0;
	g_ConfigData.PosnSpeed.fY = 4.0;
	g_ConfigData.PosnAcc.fX = 8.0;
	g_ConfigData.PosnAcc.fY = 8.0;
	g_ConfigData.PosnDec.fX = 8.0;
	g_ConfigData.PosnDec.fY = 8.0;
	g_ConfigData.PosnFinalSpeed.fX = 3.0;
	g_ConfigData.PosnFinalSpeed.fY = 3.0;
	g_ConfigData.fOrthoSlope = 0.0;
	g_ConfigData.PosnErrLimit.fX = 0.1;
	g_ConfigData.PosnErrLimit.fY = 0.1;
	g_ConfigData.fPosnTolerance = 0.0025;
	g_ConfigData.VelErrLimit.fVLimitMarginX = 0.1;
	g_ConfigData.VelErrLimit.fVErrorX = 1;
	g_ConfigData.VelErrLimit.fVLimitMarginY = 0.1;
	g_ConfigData.VelErrLimit.fVErrorY = 1;
	g_ConfigData.LongDistance.fX = 12.0;
	g_ConfigData.LongDistance.fY = 12.0;
	g_ConfigData.LongSpeed.fX = 4.0;
	g_ConfigData.LongSpeed.fY = 4.0;
	g_ConfigData.cDrillHoleOneTime = 0;
	g_ConfigData.cToolFlip = 0;
	g_ConfigData.cDriveThroughBacklash = 1;
	g_ConfigData.DrillOffset1.fX = 0;
	g_ConfigData.DrillOffset1.fY = 0;
	g_ConfigData.DrillOffset1.fYExtension = 0;
	g_ConfigData.DrillOffset2.fX = 0;
	g_ConfigData.DrillOffset2.fY = 0;
	g_ConfigData.DrillOffset2.fYExtension = 0;
	g_ConfigData.OffsetSeal.fx = 2.95;
	g_ConfigData.OffsetSeal.fy = 0.0;
	g_ConfigData.OffsetFill.fx = 4.775;
	g_ConfigData.OffsetFill.fy = 0.0;
	g_ConfigData.JogSpeed.fX = 4.0;
	g_ConfigData.JogSpeed.fY = 4.0;
	g_ConfigData.JogAcc.fX = 16.0;
	g_ConfigData.JogAcc.fY = 16.0;
	g_ConfigData.JogDec.fX = 32.0;
	g_ConfigData.JogDec.fY = 32.0;
	g_ConfigData.HomePosnYPos.fX = 0.0;
	g_ConfigData.HomePosnYPos.fY = 0.0;
	g_ConfigData.PosnLimitYPos.fMinX = 0.0;
	g_ConfigData.PosnLimitYPos.fMaxX = 0.0;
	g_ConfigData.PosnLimitYPos.fMinY = 0.0;
	g_ConfigData.PosnLimitYPos.fMaxY = 0.0;
	g_ConfigData.HomePosnYNeg.fX = 0.0;
	g_ConfigData.HomePosnYNeg.fY = 0.0;
	g_ConfigData.PosnLimitYNeg.fMinX = 0.0;
	g_ConfigData.PosnLimitYNeg.fMaxX = 0.0;
	g_ConfigData.PosnLimitYNeg.fMinY = 0.0;
	g_ConfigData.PosnLimitYNeg.fMaxY = 0.0;
	g_ConfigData.cObstructionCodeMask = 255;
	g_ConfigData.cMachineLockRequired = NoLock;
	g_ConfigData.uiALockDelay = 200;
	g_ConfigData.uiAUnlockDelay = 100;
	g_ConfigData.uiLegsLockDelay = 350;
	g_ConfigData.uiLegsUnlockDelay = 100;
	g_ConfigData.uiLegsUpDelay = 200;
	g_ConfigData.uiLegsDownDelay = 200;
	g_ConfigData.uiLowPressureDelay = 1000;
	g_ConfigData.uiLowPressureDownDelay = 300;
	g_ConfigData.uiPressureDelay = 800;
	g_ConfigData.uiPressureDownDelay = 500;
	g_ConfigData.uiLowPressure = 60;
	g_ConfigData.uiPressure = 250;
	g_ConfigData.uiAirClear = 1;
	g_ConfigData.LaserSensorOffset.fX = 0;
	g_ConfigData.LaserSensorOffset.fY = 0;
	g_ConfigData.CamOffset.fX = 0;
	g_ConfigData.CamOffset.fY = 0;
	g_ConfigData.LaserSensorAlgParam.fsearch_speed = 1;
	g_ConfigData.LaserSensorAlgParam.fseek_speed = 0.6;
	g_ConfigData.LaserSensorAlgParam.frscan_speed = 0.025;
	g_ConfigData.LaserSensorAlgParam.frscan_speed_fast = 0.025;
	g_ConfigData.LaserSensorAlgParam.fscan_speed = 0.025;
	g_ConfigData.LaserSensorAlgParam.fscan_speed_fast = 0.025;
	g_ConfigData.LaserSensorAlgParam.fprobe_diameter = 0.7;
	g_ConfigData.LaserSensorAlgParam.funknown_diameter = 0.7;
	g_ConfigData.LaserSensorAlgParam.cmode = LSMETHOD_DELTA;
	g_ConfigData.LaserSensorAlgParam.cmode_fast = LSMETHOD_DELTA;
	g_ConfigData.LaserSensorAlgParam.cuse_avg = 1;
	g_ConfigData.LaserSensorAlgParam.cfull_scan = 0;
	g_ConfigData.LaserSensorAlgParam.cgdata_sel = 1;
	g_ConfigData.LaserSensorAlgParam.cassume_posn = 0;
	g_ConfigData.LaserSensorAlgParam.cassume_posn_fast = 0;
	g_ConfigData.LaserSensorAlgParam.crect_center = 0;
	g_ConfigData.LaserSensorAlgParam.cloops = 22;
	g_ConfigData.LaserSensorAlgParam.cdelta_mode = DELTA_BASE;
	g_ConfigData.LaserSensorAlgParam.idelta_flat = 4;
	g_ConfigData.LaserSensorAlgParam.fdelta_basespan = 0.08;
	g_ConfigData.LaserSensorAlgParam.idelta_pos = 100;
	g_ConfigData.LaserSensorAlgParam.idelta_neg = -50;
	g_ConfigData.LaserSensorAlgParam.fdelta_span = 0.035;
	g_ConfigData.LaserSensorAlgParam.fdelta_edge = 0.0;
	g_ConfigData.LaserSensorAlgParam.fpc_aspect_diff = 0.004;
	g_ConfigData.LaserSensorAlgParam.fmax_aspect_diff = 0.004;
	g_ConfigData.LaserSensorAlgParam.fmax_over_exp_diameter = 0.5;
	g_ConfigData.LaserSensorAlgParam.fmax_under_exp_diameter = 0.5;
	g_ConfigData.LaserSensorAlgParam.fmax_csnk_diff = 0.001;
	g_ConfigData.LaserSensorAlgParam.fmax_over_csnk = 0.001;
	g_ConfigData.LaserSensorAlgParam.fmax_under_csnk = 0.001;
	g_ConfigData.CamAlgParam.fmove_speed = 1;
	g_ConfigData.CamAlgParam.cInfoMask = 1;
	g_ConfigData.CamAlgParam.cAMode = 0;
	g_ConfigData.CamAlgParam.cCMode = 0;
	g_ConfigData.CamAlgParam.cAux1 = 0;
	g_ConfigData.CamAlgParam.fmove_required = 0.0005;
	g_ConfigData.CamAlgParam.fmax_over_exp_diameter = 0.5;
	g_ConfigData.CamAlgParam.fmax_under_exp_diameter = 0.5;
	g_ConfigData.CamAlgParam.fmax_csnk_diff = 0.001;
	g_ConfigData.CamAlgParam.fmax_over_csnk = 0.001;
	g_ConfigData.CamAlgParam.fmax_under_csnk = 0.001;
	g_ConfigData.cVisionAutoInspect = 0;
	g_ConfigData.cProcessContinueMode = PROCESS_SINGLE;
	g_ConfigData.uiProcessOperations = 0;
	g_ConfigData.cSealClamp = 0;
	g_ConfigData.iSealPressureDelay = 800;
	g_ConfigData.iSealPressureReleaseDelay = 100;
	g_ConfigData.PrimeDelay.fdiameter1 = 0.1875;
	g_ConfigData.PrimeDelay.idelay1 = 1875;
	g_ConfigData.PrimeDelay.fdiameter2 = 0.25;
	g_ConfigData.PrimeDelay.idelay2 = 2500;
	g_ConfigData.PrimeDelay.fdiameter3 = 0;
	g_ConfigData.PrimeDelay.idelay3 = 0;
	g_ConfigData.PrimeDelay.fdiameter4 = 0;
	g_ConfigData.PrimeDelay.idelay4 = 0;
	g_ConfigData.PrimeDelay.fdiameter5 = 0;
	g_ConfigData.PrimeDelay.idelay5 = 0;
	g_ConfigData.iSealGlobDelay = 3000;
	g_ConfigData.iSealApplyDelay = 1000;
	g_ConfigData.cFillClamp_ = 0;
	g_ConfigData.iFillExtendDelay_ = 100;
	g_ConfigData.iFillRamDelay_ = 200;
	g_ConfigData.iFastenerPostDelay_ = 200;
	g_ConfigData.fToolZBase = 2.0;
	g_ConfigData.PosnDisplay.cmode = PD_DATASET;
	g_ConfigData.PosnDisplay.corigin = PD_ZERO;
	g_ConfigData.PosnDisplay.ccontent = PD_XY;
	g_ConfigData.RFIDConfig.cenabled = 1;
	g_ConfigData.RFIDConfig.cmethod = FIRST_DETECTION;
	g_ConfigData.RFIDConfig.uioptions = 0;
	g_ConfigData.RFIDConfig.uicontinuousReadCycleTime = 250;
	g_ConfigData.RFIDConfig.uiseekReadCycleTime = 50;
	g_ConfigData.RFIDConfig.fseekMove1 = -4;
	g_ConfigData.RFIDConfig.fseekMove2 = 4;
	g_ConfigData.RFIDConfig.fseekFineMove = 1;
	g_ConfigData.RFIDConfig.fseekSpeed = 1;
	g_ConfigData.RFIDConfig.fseekFineSpeed = 0.1;
	g_ConfigData.RFIDConfig.fRFIDOffset = 7;
	g_ConfigData.RFIDConfig.fseekPastBorder = 0.4;
	g_ConfigData.RFIDConfig.fminWindowSize = 0.1;
	g_ConfigData.RFIDConfig.fmaxWindowSize = 0.15;
	g_ConfigData.uiEStopClearDelay = 300;
	g_ConfigData.uiDrillButtonDelay = 300;
	g_ConfigData.cUseCutterDetect = 1;
	g_ConfigData.cJogEnableTimeout = 200;
	g_ConfigData.uiDrillCycleDelay = 6000;
	g_ConfigData.cInspectMethod = INSPECT_MANUAL;
	g_ConfigData.cCommandInspectMethod = INSPECT_MANUAL;
	g_ConfigData.ForceSensorCalibration.iZeroX = 0;
	g_ConfigData.ForceSensorCalibration.iZeroY = 0;
	g_ConfigData.ForceSensorCalibration.iZeroZ = 0;
	g_ConfigData.ForceSensorCalibration.iCountsPerGX = 0;
	g_ConfigData.ForceSensorCalibration.iCountsPerGY = 0;
	g_ConfigData.ForceSensorCalibration.iCountsPerGZ = 0;
	g_ConfigData.ForceLimits.uiSensorInterval = 100;
	g_ConfigData.ForceLimits.uiMinUpdateDelta = 200;
	g_ConfigData.ForceLimits.cActive = 0;
	g_ConfigData.ForceLimits.cCurrentUnderMethod = 0;
	g_ConfigData.ForceLimits.uiCurrentOverX = 2000;
	g_ConfigData.ForceLimits.uiCurrentUnderX = 2000;
	g_ConfigData.ForceLimits.uiCurrentOverY = 2000;
	g_ConfigData.ForceLimits.uiCurrentUnderY = 2000;
	g_ConfigData.ForceLimits.uiFullGravX = 2000;
	g_ConfigData.ForceLimits.uiFullGravY = 2000;
	g_ConfigData.ForceLimits.uiFlatForceX = 300;
	g_ConfigData.ForceLimits.uiFlatForceY = 300;
	g_ConfigData.cProbeFlags = 3;
	g_ConfigData.MOCal.uim1 = 512;
	g_ConfigData.MOCal.uim2 = 512;
	g_ConfigData.MOCal.uim3 = 512;
	g_ConfigData.MOCal.uim4 = 512;
	g_ConfigData.MOCal.uim5 = 512;
	g_ConfigData.MOCal.uim6 = 512;
	g_ConfigData.fMaxKholeDistanceCheck = 48;
	g_ConfigData.fMaxEdgeShiftProbeAccept = 0.5;
	g_ConfigData.cAllowDrillBeyondShiftLimits = 0;
	g_ConfigData.SystemComponents.cDrill = 1;
	g_ConfigData.SystemComponents.cFastener = 0;
	g_ConfigData.SystemComponents.cFastenerTray = 0;
	g_ConfigData.SystemComponents.cAux1 = 0;
	g_ConfigData.SystemComponents.cAux2 = 0;
	g_ConfigData.SystemComponents.cAux3 = 0;
	g_ConfigData.SystemComponents.cAux4 = 0;
	g_ConfigData.SystemComponents.cAux5 = 0;
	g_ConfigData.uiSpritzDurationMs = 200;
	g_ConfigData.uiBurstOnDurationMs = 100;
	g_ConfigData.uiBurstIntervalMs = 500;
	g_ConfigData.AngleSensorANegCalibration.flevel = 0;
	g_ConfigData.AngleSensorANegCalibration.finch_volts = 1;
	g_ConfigData.AngleSensorANegCalibration.fmin_valid = 0;
	g_ConfigData.AngleSensorANegCalibration.fmax_valid = 10;
	g_ConfigData.AngleSensorAPosCalibration.flevel = 0;
	g_ConfigData.AngleSensorAPosCalibration.finch_volts = 1;
	g_ConfigData.AngleSensorAPosCalibration.fmin_valid = 0;
	g_ConfigData.AngleSensorAPosCalibration.fmax_valid = 10;
	g_ConfigData.fAngleSensorABaseWidth = 1.300;
	g_ConfigData.AngleSensorMCCalibration.flevel = 0;
	g_ConfigData.AngleSensorMCCalibration.fdeadzone = 8000;
	g_ConfigData.AngleSensorMCCalibration.fspeed_slope = 1;
	g_ConfigData.AngleSensorMCCalibration.fmin_valid = -5;
	g_ConfigData.AngleSensorMCCalibration.fmax_valid = 5;
	g_ConfigData.AngleSensorMCCalibration.fCountsPerDegree = 1;
	g_ConfigData.fAAxisMoveSpeed = 0.6;
	g_ConfigData.ClampStain.iCountsFree = 0;
	g_ConfigData.ClampStain.iCountsClamped = 2048;
}
//MakeOID-Section::END



