//ToolManagementSmartTool.c
//Generated by MakeOID20131018.1 
//Preserve any customized code if required.
#include "ToolManagementSmartTool.h"



//MakeOID-Section:: OID NAMES ARRAY

char * pszOIDNamesToolManagement[] = {
	"TOOL_MGMT",
	"TOOL_REC",
	"OID_MAX_NUMBER_ToolManagement"
};

//MakeOID-Section::END


//MakeOID-Section:: Global Smart Tool ID And Version Constant Defines 

const char * SmartToolTypeToolManagement = "ToolManagement";

const char * ToolManagementSysVersion = "null";

const uint16 ToolManagementCOMVersion = 0;

td_SmartTool g_ToolManagementSmartTool = { "ToolManagement", 400, TOOLMANAGEMENT_OID_MAX_NUMBER, pszOIDNamesToolManagement };

//MakeOID-Section:: CONFIG DECLARATION

td_ToolManagementConfigData g_ToolManagementConfigData;

//MakeOID-Section::END


//MakeOID-Section:: GLOBAL DECLARATIONS

//MakeOID-Section::END


//MakeOID-Section:: CONFIG DEFAULTS

void ToolManagementInitConfig(void)
{
}
//MakeOID-Section::END


